spring:
  profiles: 
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.zpr.springcloud.entities       # 所有Entity别名类所在的包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true
info:
  app.name: zola-microspringcloud
  company.name: www.zola.com
  build.artifactId: @project.artifactId@     # $不起作用，@可以加引号也可以不加
  build.version: @project.version@
security: 
  basic: 
    enabled: false
---
server:
  port: 8002
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.zpr.springcloud.entities       # 所有Entity别名类所在的包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件


eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8002
    prefer-ip-address: true
info:
  app.name: zola-microspringcloud
  company.name: www.zola.com
  build.artifactId: @project.artifactId@     # $不起作用，@可以加引号也可以不加
  build.version: @project.version@
