spring:
  profiles:
  active:
  - dev
---
server:
  port: 8080

spring:
  profiles: dev
  application:
    name: microservicecloud-config-consumer-dept-client
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 8081

spring:
  profiles: test
  application:
    name: microservicecloud-config-consumer-dept-client
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/
